Check if a result is a proper id

diff --git a/render-map b/render-map
--- a/render-map
+++ b/render-map
@@ -25,7 +25,13 @@ function render-map {
   if [[ ${1-} && $1 != -* ]]; then
     name=$1
     shift
-    set -- -t "$name" --osmid="$(sudo -i -u postgres psql -A -c "SELECT osm_id FROM planet_osm_polygon WHERE name ILIKE '\''$name'\'' LIMIT 1" -d maposmatic | sed -n '2p')" "$@"
+    id=$(sudo -i -u postgres psql -A -c "SELECT osm_id FROM planet_osm_polygon WHERE name ILIKE '\''$name'\'' LIMIT 1" -d maposmatic | sed -n '2p')
+    if [[ $id =~ ^-?[0-9]+$ ]]; then
+      set -- -t "$name" --osmid="$id" "$@"
+    else
+      echo "Not found: $name"
+      exit 1
+    fi
   fi
   ./render.py -l multi_page --paper-format="Din A5" "$@"
   if [[ -f ./links.ps && -f ./toc.ps ]]; then
